### ISSUE TITLE
Should bitwise operators be added? And custom dropdowns?

### ISSUE THREAD

**Issue by NoMod-Programming** [GRA0007/Blue#4]
I was looking through some old rejected pull requests on the main branch of LLK/Scratch-Flash, and I found two feature requests that might seem like a good idea to incorporate into blue. 
The first one is [bitwise operators](https://github.com/LLK/scratch-flash/pull/474). The second one is [custom dropdowns](https://github.com/LLK/scratch-flash/pull/419).

Let me know what you think about them
- NoMod

**Comment by GRA0007** [comment]
I think that the bitwise operators are definitely a good thing to add, everyone seems to be adding them to their own scratch mods. :P Would the custom dropdowns be something that works with extensions?

**Comment by NoMod-Programming** [comment]
Yes. Custom dropdowns would work with extensions.

**Comment by NoMod-Programming** [comment]
Done.
