### ISSUE TITLE
Color blocks should return colors

### ISSUE THREAD

**Issue by GRA0007** [GRA0007/Blue#5]
The color blocks should be returning colors rather than strings. ^-^

**Comment by NoMod-Programming** [comment]
This might take a bit longer than I expected to completely implement, as the reporter bubbles don't seem to like displaying a color.

**Comment by GRA0007** [comment]
Yeah, if you have a look at djdolphin's Jackalope mod, they seem to have made a new type of reporter that returns colors in the reporter bubbles.

**Comment by NoMod-Programming** [comment]
Alright. I'll take a look at it and get implemented soon!

**Comment by NoMod-Programming** [comment]
Done
