### ISSUE TITLE
Editing a custom c-block turns it into a normal block

### ISSUE THREAD

**Issue by BookOwl** [GRA0007/Blue#6]

**Comment by NoMod-Programming** [comment]
Can you provide a screenshot? I'm not understanding what you are saying.

**Comment by GRA0007** [comment]
I think it happens when you click edit on a custom block that can run blocks inside it, it turns into a normal custom block.

**Comment by BookOwl** [comment]
@GRA0007 exactly

**Comment by NoMod-Programming** [comment]
Alright, I just fixed this.
